- name: Create Jenkins Jobs
  hosts: localhost
  roles:
    - jenkins
  vars:
    folders:
      - { folder_name: "CI-Pipelines" }
      - { folder_name: "Infra-Jobs" }
      - { folder_name: "Deployment-Jobs" }
    mjobs:
      - { job_name: "cart", repo_name: "https://github.com/SPOORNACHANDRA/cart", folder_name: "CI-Pipelines" }
    sjobs:
      - { job_name: "roboshop-terraform", repo_name: "https://github.com/SPOORNACHANDRA/roboshop-terraform", folder_name: "Infra-Jobs" }