- name: copy config file - {{item.folder_name}}
  ansible.builtin.copy:
    src: folder.xml
    dest: /tmp/folder.xml


- name: Create a folder - {{item.folder_name}}
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/folder.xml') }}"
    name: "{{item.job_name}}"
    password: admin123
    url: http://jenkinsip:8080
    user: admin