- name: copy config file - {{item.job_name}}
  ansible.builtin.copy:
    src: sjob.xml
    dest: /tmp/sjob.xml


- name: Create a job - {{item.job_name}}
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/sjob.xml') }}"
    name: "{{item.job_name}}"
    password: admin123
    url: http://jenkinsip:8080
    user: admin